name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "frappe/backport"
          path: ./actions
          ref: develop
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run backport
        uses: ./actions/backport
        with:
<<<<<<< HEAD
          token: ${{secrets.BACKPORT_BOT_TOKEN}}
=======
          token: ${{secrets.RELEASE_TOKEN}}
>>>>>>> 125a352bc2 (fix: allow all dispatch address for drop ship invoice)
          labelsToAdd: "backport"
          title: "{{originalTitle}}"
